# Generated by Django 3.1.2 on 2020-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry_edited_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_profile_id', models.IntegerField()),
                ('edited_by', models.CharField(max_length=40)),
                ('edited_time', models.DateTimeField(auto_now_add=True)),
                ('previous_title', models.CharField(max_length=50)),
                ('current_title', models.CharField(max_length=50)),
                ('previous_content', models.TextField()),
                ('current_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='entry_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=40)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('read_times', models.IntegerField(default=0)),
                ('last_read', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
